[tool.poetry]
name = "cloelib"
version = "0.8.2"
description = "cloelib is a flexible and efficient library designed to compute cosmological observables for CLOE (Cosmology Likelihood for Observables in Euclid)"
authors = [
    "M. Bonici <marco.bonici@uwaterloo.ca>",
    "G. Cañas-Herrera <guadalupe.canasherrera@esa.int>",
    "P. Carrilho <pedro.carrilho@ed.ac.uk>",
    "S. Casas <casas@physik.rwth-aachen.de>",
    "C. Moretti <cmoretti@sissa.it>",
    "A. Pezzotta <andrea.pezzotta@inaf.it>",
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
interpax = "0.3.3"
jax = "0.4.38"
numpy = "<2.0"
quadax = "0.2.7"
scipy = "<1.14"
pytest = "8.3.5"
pytest-cov = "6.1.1"
pytest-pydocstyle = "2.4.0"
mypy = "1.17"

[tool.poetry.extras]
camb = ["camb"]
hmcode2020emu = ["HMcode2020Emu"]
comet-emu = ["comet-emu"]

[tool.poetry.dependencies.tensorflow]
version = "==2.13"
optional = true

[tool.poetry.dependencies.HMcode2020Emu]
git = "https://github.com/MariaTsedrik/HMcode2020Emu.git"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--verbose --pydocstyle --cov=cloelib"

[tool.black]
force-exclude = "tests_cluster/benchmark_values.py"

[tool.isort]
profile = "black"
