[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "cloelib"
description = "cloelib is a flexible and efficient library designed to compute cosmological observables for CLOE (Cosmology Likelihood for Observables in Euclid)"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "M. Bonici", email = "marco.bonici@uwaterloo.ca" },
    { name = "G. Cañas-Herrera", email = "canasherrera@strw.leidenuniv.nl" },
    { name = "P. Carrilho", email = "p.carrilho@herts.ac.uk" },
    { name = "S. Casas", email = "s.casas@protonmail.com" },
    { name = "C. Moretti", email = "cmoretti@sissa.it" },
    { name = "A. Pezzotta", email = "andrea.pezzotta@inaf.it" }
]

dependencies = [
    "interpax",
    "jax",
    "numpy>2.0",
    "quadax",
    "scipy>1.14",
    "pytest",
    "pytest-cov",
    "mypy",
    "pyinstrument",
    "cosmolib"
]
dynamic = ["version"]

[project.optional-dependencies]
camb = ["camb==1.6.5"]
classy = ["classy==3.3.4"]
comet-emu = ["comet-emu"]
hmcode2020emu = ["HMcode2020Emu @ git+https://github.com/MariaTsedrik/HMcode2020Emu.git"]
euclidemu2 = ["euclidemu2==1.4.3"]
pylevin = ["pylevin"]
mpmath = ["mpmath"]
tensorflow = ["tensorflow"]
tf-keras = ["tf-keras"]
react = [
    "MGemu @ git+https://github.com/nebblu/MGEmus.git",
    "tensorflow",
    "tf-keras",
]
cosmopower-jax=["cosmopower-jax"]
baccoemu = ["baccoemu"]
hiclassy = ["hiclassy==3.3.4"]
emantis = ["emantis>=1.2.1"]
pbjcosmo = ["pbjcosmo"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "cloelib/_version.py"

[tool.pytest.ini_options]
addopts = "--verbose --cov=cloelib"

[tool.hatch.metadata]
allow-direct-references = true
