"""
Characterization ("golden") tests for `ShearTracer`/`PositionsTracer`/
`CMBLensingTracer`'s `get_window`/`get_Cl` output.

These pin `get_window`/`get_Cl` outputs for `ShearTracer` (with a non-zero
NLA intrinsic-alignment contribution), `PositionsTracer` (all three
`galaxy_bias_model` variants), and `CMBLensingTracer` against known-good
reference values. Their purpose is to make any accidental numeric drift in
this code fail loudly here first. They intentionally do not re-derive the
physics or assert anything about *correctness* - only that today's exact
output is preserved (in particular: they guarantee the Contribution-based
architecture in `cloelib.observables.photo` - `LensingContribution`,
`NLAContribution`, `GalaxyBiasContribution`,
`MagnificationContribution` composed via `get_contributions()` - reproduces
the same output as directly-summed window methods, for every default
(non-TATT) configuration).

Reference values live in `tests/fixtures/photo_tracers_baseline.npz`,
generated by `tests/fixtures/generate_photo_tracers_baseline.py` (not
collected by pytest; regenerate only if a change is *intended* to alter
these outputs). Note: `tests/fixtures/` is used rather than a `data/`-named
directory because this repo's `.gitignore` excludes `*/data/*` repo-wide.
"""

from pathlib import Path

import numpy as np
import pytest

from cloelib.cosmology.camb_cosmology import (
    CAMBBackground,
    CAMBNonLinearPerturbations,
)
from cloelib.cosmology.jax_cosmology import JAXBackground, JAXLinearPerturbations
from cloelib.observables.cmb import CMBLensingTracer
from cloelib.observables.photo import PositionsTracer, ShearTracer
from cloelib.summary_statistics.angular_two_point import AngularTwoPoint

BASELINE_PATH = Path(__file__).parent / "fixtures" / "photo_tracers_baseline.npz"


@pytest.fixture(scope="module")
def baseline():
    """Reference arrays captured from the pre-refactor codebase."""
    with np.load(BASELINE_PATH) as data:
        return {k: data[k] for k in data.files}


@pytest.fixture(scope="module")
def tracer_setup():
    """Rebuild the exact tracer setup used to generate the baseline fixture."""
    H0 = 67.7
    h = H0 / 100.0
    omch2 = 0.12
    Omega_cdm0 = omch2 / h**2
    ombh2 = 0.022
    Omega_b0 = ombh2 / h**2

    background = CAMBBackground(
        H0=H0,
        Omega_b0=Omega_b0,
        Omega_cdm0=Omega_cdm0,
        Omega_k0=0.0,
        As=2e-9,
        ns=0.96,
        alpha_s=0.0,
        mnu=0.06,
        w0=-1.0,
        wa=0.0,
        gamma_MG=0.0,
        N_mnu=1,
    )

    z_auto = np.linspace(0.01, 1100.0, 100)
    z = np.linspace(0.2, 2.0, 20)
    perturbations = CAMBNonLinearPerturbations(background, None, z_auto)

    n_z_bins = 2
    dndz = np.ones((n_z_bins, len(z)))
    dndz /= np.trapezoid(dndz, z, axis=1)[:, None]

    # Non-zero AIA/CIA/EtaIA so the NLA intrinsic-alignment term (the code
    # path touched by the growth_factor(...)[:, 1] landmine) is genuinely
    # exercised, not silently multiplied by zero.
    nuisance_shear = {
        **{f"multiplicative_bias_{i + 1}": 0.0 for i in range(n_z_bins)},
        **{f"dz_shear_{i + 1}": 0.0 for i in range(n_z_bins)},
        **{f"width_shear_{i + 1}": 1.0 for i in range(n_z_bins)},
        "AIA": 1.0,
        "CIA": 0.0134,
        "EtaIA": -0.41,
    }

    nuisance_pos_common = {
        **{f"dz_pos_{i + 1}": 0.0 for i in range(n_z_bins)},
        **{f"width_pos_{i + 1}": 1.0 for i in range(n_z_bins)},
        **{f"magnification_bias_{i + 1}": 0.3 for i in range(n_z_bins)},
    }

    nuisance_pos_per_bin = {
        **nuisance_pos_common,
        "b1_photo_bin0": 1.1,
        "b1_photo_bin1": 1.4,
    }
    nuisance_pos_poly = {
        **nuisance_pos_common,
        "b1_photo_poly0": 1.0,
        "b1_photo_poly1": 0.1,
        "b1_photo_poly2": 0.0,
        "b1_photo_poly3": 0.0,
    }

    shear_tracer = ShearTracer(
        perturbations=perturbations,
        dndz=dndz,
        z=z,
        nuisance_params=nuisance_shear,
        ia_model="NLA",
    )
    pos_per_bin = PositionsTracer(
        perturbations=perturbations,
        dndz=dndz,
        z=z,
        galaxy_bias_model="per_bin",
        nuisance_params=nuisance_pos_per_bin,
    )
    pos_per_bin_int = PositionsTracer(
        perturbations=perturbations,
        dndz=dndz,
        z=z,
        galaxy_bias_model="per_bin_int",
        nuisance_params=nuisance_pos_per_bin,
    )
    pos_poly = PositionsTracer(
        perturbations=perturbations,
        dndz=dndz,
        z=z,
        galaxy_bias_model="poly",
        nuisance_params=nuisance_pos_poly,
    )
    cmbl_tracer = CMBLensingTracer(perturbations=perturbations, z=z)

    nl = 6
    ells = np.logspace(1.0, np.log10(200), nl)
    ks = np.asarray(perturbations.k)

    return {
        "z": z,
        "ells": ells,
        "ks": ks,
        "shear_tracer": shear_tracer,
        "pos_per_bin": pos_per_bin,
        "pos_per_bin_int": pos_per_bin_int,
        "pos_poly": pos_poly,
        "cmbl_tracer": cmbl_tracer,
    }


def _assert_matches(actual, expected, label):
    np.testing.assert_allclose(
        np.asarray(actual),
        expected,
        rtol=1e-8,
        atol=0.0,
        err_msg=f"{label} no longer matches the pre-refactor reference value",
    )


def test_baseline_grids_unchanged(tracer_setup, baseline):
    """Sanity: ells/ks grids used to build the fixture haven't drifted."""
    np.testing.assert_allclose(tracer_setup["ells"], baseline["ells"])
    np.testing.assert_allclose(tracer_setup["ks"], baseline["ks"])


@pytest.mark.parametrize(
    "tracer_key,baseline_key",
    [
        ("shear_tracer", "window_shear"),
        ("pos_per_bin", "window_pos_per_bin"),
        ("pos_per_bin_int", "window_pos_per_bin_int"),
        ("pos_poly", "window_pos_poly"),
        ("cmbl_tracer", "window_cmbl"),
    ],
)
def test_get_window_matches_baseline(tracer_setup, baseline, tracer_key, baseline_key):
    tracer = tracer_setup[tracer_key]
    z = tracer_setup["z"]
    _assert_matches(tracer.get_window(z), baseline[baseline_key], tracer_key)


@pytest.mark.parametrize(
    "tracer1_key,tracer2_key,prefix",
    [
        ("shear_tracer", "shear_tracer", "she_she"),
        ("pos_per_bin", "pos_per_bin", "pos_pos"),
        ("pos_per_bin", "shear_tracer", "pos_she"),
        ("cmbl_tracer", "cmbl_tracer", "cmbl_cmbl"),
        ("cmbl_tracer", "pos_per_bin", "cmbl_pos"),
        ("cmbl_tracer", "shear_tracer", "cmbl_she"),
    ],
)
def test_get_cl_matches_baseline(
    tracer_setup, baseline, tracer1_key, tracer2_key, prefix
):
    tracer1 = tracer_setup[tracer1_key]
    tracer2 = tracer_setup[tracer2_key]
    ells = tracer_setup["ells"]
    ks = tracer_setup["ks"]

    two_point = AngularTwoPoint(tracer1, tracer2)
    cl = two_point.get_Cl(ells, 0, ks)

    matched_any = False
    for key, spectrum in cl.items():
        flat_key = f"cl_{prefix}_" + "_".join(str(k) for k in key)
        assert flat_key in baseline, (
            f"{flat_key} present in get_Cl() output but missing from baseline "
            "fixture - baseline needs regenerating deliberately, not silently"
        )
        _assert_matches(spectrum.array, baseline[flat_key], flat_key)
        matched_any = True

    assert matched_any, f"get_Cl() returned no entries for pair '{prefix}'"


def test_growth_factor_ks_handling_on_jax_backend():
    """Regression test for the growth_factor(...)[:, 1] / `.k` handling.

    `ShearTracer.get_window_IA` cannot unconditionally read
    `self.perturbations.k` and index `growth_factor(...)[:, 1]`: the JAX
    backends never set a `.k` attribute (they ignore the `ks` argument to
    `growth_factor` entirely) and return a 1D D(z), not a 2D D(z, k) - that
    combination raises `AttributeError` for every JAX-backend
    `Perturbations`. `get_window_IA` handles this via
    `getattr(self.perturbations, "k", None)` plus an `ndim`-based branch
    (`photo/shear.py`), exercised directly here against a JAX
    `Perturbations` instance rather than through `get_window_IA`/
    `ShearTracer.get_window`, because those additionally call
    `Background.Omega_m(0.0)` with a bare scalar, which the JAX backend's
    `Omega_m` does not support - a separate, pre-existing gap
    (`JAXBackground.Omega_m` iterates its `zs` argument), out of scope here.
    """
    background = JAXBackground(
        H0=67.7,
        Omega_b0=0.05,
        Omega_cdm0=0.25,
        Omega_k0=0.0,
        As=2e-9,
        ns=0.96,
        mnu=0.0,
        w0=-1.0,
        wa=0.0,
        gamma_MG=0.0,
        N_mnu=0,
    )
    perturbations = JAXLinearPerturbations(background=background)
    z = np.linspace(0.2, 2.0, 10)

    # The gap this fix guards against: no `.k` attribute on this backend.
    assert getattr(perturbations, "k", None) is None

    ks = getattr(perturbations, "k", None)
    Dz_raw = perturbations.growth_factor(z, ks)
    Dz = Dz_raw[:, 1] if getattr(Dz_raw, "ndim", 1) == 2 else Dz_raw

    assert np.asarray(Dz).shape == (len(z),)
    assert np.all(np.isfinite(np.asarray(Dz)))
