name: Build and Check

on:
  push:
    branches:
      - main
      - cluster_structure
  pull_request:

jobs:
  build-gcc-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.13' 
    - name: Install prereq using pip
      run: |
        pip install astropy cython black
        pip install camb classy jax
        pip install pyinstrument

    - name: Install the package
      run: |
        pip install .
    - name: Run the unit tests
      run: |
        pip install pytest pytest-cov
        pytest tests_cluster/ --cov=cloelib/ --ignore=tests_cluster/benchmark_values.py
      env:
        DISPLAY: test
#    - name: Install Sphinx prereq
#      run: |
#        conda install -c conda-forge sphinx sphinx_rtd_theme nbconvert pandoc ipython ipython_genutils
